# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Marlow's Listener
tagline:             not having to think about what you are going to say when you can decently interrupt
url:                 http://technocrat.githup.io
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Richard Careaga
  #url:              https://twitter.com/mdo
  email:             public@careaga.net

# Custom vars
#version:             1.0.0
#github:
#  repo:              https://github.com/poole/poole
